// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class WordpressTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
 

 
  public static void main(String[] args) {
	  
	System.setProperty("webdriver.gecko.driver","C:\\tools\\selenium\\web-drivers\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  //public void wordpress() {
    driver.get("http://13.127.223.242/wp-login.php/");
    driver.findElement(By.id("user_login")).sendKeys("admin");
    driver.findElement(By.id("user_pass")).sendKeys("admin123");
    driver.findElement(By.id("wp-submit")).click();
    driver.findElement(By.cssSelector(".welcome-panel-content > h2")).click();
    assertThat(driver.findElement(By.cssSelector(".welcome-panel-content > h2")).getText(), is("Welcome to WordPress!"));
  }
}
